# Generated by Django 5.1.1 on 2024-10-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_address_id_alter_booking_id_and_more'),
        ('services', '0004_alter_service_id_alter_servicetype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(related_name='bookings', to='services.service'),
        ),
    ]
